### ISSUE TITLE
cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

### ISSUE THREAD

**Issue by Syed044** [BenAAndrew/Voice-Cloning-App#14] opened 2021-04-04 08:21 UTC
i m trying use my own audio and text, this is the error i m having.

cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

using windows version.
python version is giving another error.

 File "main.py", line 4, in <module>
    from engineio.async_drivers import threading
ModuleNotFoundError: No module named 'engineio'

I m new to both worlds, is there anything I m not doing?

**Comment by BenAAndrew** [comment] 2021-04-04 11:36
@Syed044 Sounds like a few different problems. Firstly, what version are you using?

**Comment by Syed044** [comment] 2021-04-04 12:12
the latest windows version.
on python it on 3.8

**Comment by Syed044** [comment] 2021-04-04 12:14
i have my own audio in wav, 22050  and transcript of that audio in text file utf8.  However when i m trying to build dataset its throwing that error.

**Comment by BenAAndrew** [comment] 2021-04-04 12:20
@Syed044 sorry I mean which build are you using. Are you using the latest one 0.4.1: https://github.com/BenAAndrew/Voice-Cloning-App/releases/tag/v0.4.1 ?

**Comment by Syed044** [comment] 2021-04-04 12:21
First of all,

Thank you for quick response, yes i m using the 0.4.1.

**Comment by BenAAndrew** [comment] 2021-04-04 12:24
Ok, could you send me the data you're trying to use. My email is benandrew89@gmail.com

**Comment by BenAAndrew** [comment] 2021-04-04 12:56
@Syed044 Unfortunately I've just realised only English is currently supported.

**Comment by BenAAndrew** [comment] 2021-04-04 13:00
Closing because the bug is caused by non-English datasets

**Closed by BenAAndrew** 2021-04-04 13:00 UTC
Labels: bug, help wanted
