### ISSUE TITLE
Cannot import dataset

### ISSUE THREAD

**Issue by trevornestor** [BenAAndrew/Voice-Cloning-App#16] opened 2021-04-05 15:34 UTC
I get an error that says:

cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

I get this error when trying to use your app when generating a dataset
then when I press train it says [Errno 2] No such file or directory: 'data\\datasets\\CLEAN\\metadata.csv'

The thing is, I thought that the whole point of generating a dataset would be to create the csv file

I have the txt file with the transcription and the wav file which is 16 bit pcm wav file mono 20500
I also tried inputting a pre-transcribed dataset of my own in a zip file but I get an error that says that there is no metadata.csv file even though I included one
basically it's a folder that is zipped that has an inner wavs folder and a metadata.csv file with the following contents:

wavs/1.wav|Good morning, this morning we learned that our economy created nine hundred thousand jobs in march.
wavs/2.wav|It means the first two months of our administration, has seen more new jobs created, in the first two months than any administration in history.
wavs/3.wav|We still have a long way to go, to get our economy back on track after the worst economic and job crisis in over a century.
wavs/4.wav|Well my, message to the american people is this, help is here, opportunity is coming.
wavs/5.wav|Hard working men and women who have struggled through this pandemic.
wavs/6.wav|Who will never given up, and are determined to get the country back on track, as well as their families.
wavs/7.wav|And I think it's also, a reflection of two things we are doing here.
wavs/8.wav|First, the new economic strategy we've launched, one focused on building from the bottom up and out.
wavs/9.wav|The one that puts government on the side of working people and rewards work, not wealth.
wavs/10.wav|We invest in the american people, it's not just those at the top that make our economy grow, they're the ones that are making it grow, ordinary americans.
wavs/11.wav|We saw the economy gain traction in march, as the american rescue plan moved and got passed, bringing new hope into our country.
wavs/12.wav|We're gonna continue to continue to implement that law in the weeks ahead.
wavs/13.wav|By april seventh, next week, over a hundred and thirty million households will have gotten their one thousand and four hundred dollar rescue check.
wavs/14.wav|Funds, are on their way to local communities to put educators, healthcare workers, home healthcare aides, police, firefighters, sanitary workers, back on their jobs.
wavs/15.wav|We're getting more aid for small businesses, we're also gonna hang an open sign again on the door to rehire folks that had to be let go.
wavs/16.wav|In the months ahead, the new child care tax credit, will cut taxes and provide health to millions of families to young children.
wavs/17.wav|There's nothing, nothing, I know you're tired of hear me say this but I mean there's nothing the american people can not do if you give them a chance.
wavs/18.wav|And the american rescue plan does precisely that, hard working middle class folks, at long last.
wavs/19.wav|Secondly, today's report also reflects the progress, we've made on my other key priority, getting the american people vaccinated.
wavs/20.wav|Turned around a slow moving vaccination program into being the envy of the world.
wavs/21.wav|Yesterday, we set an all time record for thursday vaccinations, ending a seven day period, that was the first ever, where we administered twenty million shots.

not sure if I typed up the text in the csv data file right though, there is no information for how to format the text inside of it

**Comment by gabcodedev** [comment] 2021-04-05 18:30
The issue that I have is somewhat related to this one. When importing a dataset my audios are all fine, so after transcribing the audios I convert my txt file into a csv file (I do it like in the example David Attenborough database). I also remove the "wavs/" part because in the example database that isn't included. The thing is that all looks perfect so I zip metadata.csv with the wavs folder together and I import it. Now comes the weird part, after importing it succesfully I go to the training and I see the "NaN hours, etc..." see issue #10  . This means that if I attempt to train as it is now it won't work because something is wrong (in this case is the metadata.csv file and I'll tell you how I know it in a sec). I know that the problem is the metadata.csv because I replaced it with the metadata.csv from David Attenborough's database and it didn't show the NaN error anymore (I have the same amount of audio samples). Obviously the transcriptions are different so it doesn't make sense to train it. I know this program is still in "beta" but it would be very good if the author provided some kind of in depth guide for creating the metadata.csv file, because the author made some videos but this videos are only for amazon audio books, but, what if I want to use other sources? Also I have another question for the author of the program, when I train (in the David Attenborough's database, as it is the only one that isn't causing NaN time problems) after some seconds it opens again the main page (localhost:5000) and kind of restarts but the train tab is still opened and if I wait some time it doesn't make any progress, do I have to wait more time? And why is a new tab opening with the main page every time I train, is this a bug? I am using this program because the Tacotron 2 Google colab project doesnt work well with a high amount of audio samples, it throws ram errors, and what python version do you recommend for this program, the latest or any particular version? Sorry for making all this questions but the videos are very basic and don't explain correctly how this works. Greetings.

**Comment by BenAAndrew** [comment] 2021-04-06 16:46
@trevornestor @gabcodedev There's a lot of stuff to unpack here so I'll focus on the issue both of you have in common which is trying to import the dataset.

The format of each dataset requires:
-  A file called metdata.csv containing the labels 
-  A folder called wavs containing the audio. 

@trevornestor @gabcodedev Could you both firstly check that the metadata.csv file and wavs folder are in the root of your dataset (look in `data\datasets\<your dataset name>`)?

Also @gabcodedev, the issue with "NaN" prediction is because the app uses the audio file names to speed up calculating the size. If you look at a David Attenborough dataset you'll note the audio have names like `1000_2000.wav`. This denotes that this clip was taken from 1000ms to 2000ms and is therefore 1000ms (1s) long. I'll look into adding slower calculation way measuring each file duration this week.

**Comment by trevornestor** [comment] 2021-04-06 17:49
I have a folder that has the Voice Cloning app folder and the Training Data folder

Inside my training data folder at the root of it is the csv file and a folder called wavs which contains all the wavs

Now I don't really know how to format the csv file as I don't think you covered it in your tutorial but I wrote inside of it in a format which some youtuber said to do for using tacotron, but instead of a csv file he just uses a text file.

CSV stands for comma separated values, maybe I need commas? How do I format the inside of the csv file? In the video the youtuber said to just put periods at the end of sentences.

I don't know what gabcodedev's problem means but I get this error when trying to generate a dataset:
cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

Then when I try to train I get:
[Errno 2] No such file or directory: 'data\datasets\CLEAN\metadata.csv'

I'm like one hundred percent sure the csv file is in there but maybe I need to rename the folder "data" and rename the wavs folder "dataset" and then put a folder in dataset called "CLEAN"

But I mean I don't even have a folder named "CLEAN" that is just what I named the dataset in the app

I really don't know like maybe if I just put the metadata.csv file in just every possible folder location it will eventually find it, lol

**Comment by BenAAndrew** [comment] 2021-04-06 19:25
@trevornestor The error `No such file or directory: 'data\datasets\CLEAN\metadata.csv'` means that there is no file for that path. If you go to the folder where  `Voice-Cloning-App.exe` is there will be a folder called `data` in the same location. That is the data folder referred to in the error. Go into this folder, then datasets, then CLEAN and in that folder, there should be the metadata file that is currently missing. 

Also, in the metadata file there should not be `wavs/` at the start of each line, just the filename (i.e. `1.wav|Good morning ...`)

**Comment by BenAAndrew** [comment] 2021-04-07 20:02
@trevornestor @gabcodedev Release 0.5.2 has been published to improve some of your dataset import issues. Please give it a go and get back to me

**Comment by gabcodedev** [comment] 2021-04-09 13:52
Okay I have my wavs folder and my metadata.csv, all is working good except that when I train it loads all data (I can see it on the "embedded console", and then after some seconds opens a new tab in my browser with the main page (localhost:5000). If I switch to the training tab and I wait for some time it doesn't make any progress. Can you help me with this please?

**Comment by BenAAndrew** [comment] 2021-04-10 11:53
Closing as this is a new issue being covered in https://github.com/BenAAndrew/Voice-Cloning-App/issues/18

**Closed by BenAAndrew** 2021-04-10 11:53 UTC
Labels: bug
