### ISSUE TITLE
 'WaveGlow' object has no attribute 'encode'

### ISSUE THREAD

**Issue by johnpaulbin** [BenAAndrew/Voice-Cloning-App#28] opened 2021-04-24 18:25 UTC
Running:
`synthesize(model, waveglow, text, inflect_engine, graph, audio); print(""); ipd.Audio("audio.wav", rate=22050)`

Brings:
`AttributeError: 'WaveGlow' object has no attribute 'encode'`

Both waveglow model and tacotron model is up to date and exists, seems like the the most recent release caused this.

**Comment by BenAAndrew** [comment] 2021-04-24 19:13
The implementation of synthesize has changed: https://github.com/BenAAndrew/Voice-Cloning-App/blob/aab56c0c1deac864498cc5a11162a7d73527e729/synthesis/synthesize.py#L88

You should now call it like:
`synthesize(model, text, inflect_engine, graph=graph, audio=audio, vocoder=waveglow, vocoder_type="waveglow")`

**Comment by BenAAndrew** [comment] 2021-04-24 19:39
@johnpaulbin did this fix the issue or are there still problems? Also if you are interested you can also use the hifi-gan vocoder now https://github.com/jik876/hifi-gan

**Comment by BenAAndrew** [comment] 2021-04-25 16:29
Closing as this is not a bug or feature improvement. Please put a message in the discord if you need any more assistance with this

**Closed by BenAAndrew** 2021-04-25 16:29 UTC
