### ISSUE TITLE
Training unexpectedly crashes

### ISSUE THREAD

**Issue by gabcodedev** [BenAAndrew/Voice-Cloning-App#18] opened 2021-04-09 14:17 UTC
Okay I have my wavs folder and my metadata.csv, all is working good except that when I train it loads all data (I can see it on the "embedded console", and then after some seconds opens a new tab in my browser with the main page (localhost:5000). If I switch to the training tab and I wait for some time it doesn't make any progress. Can you help me with this please?

**Comment by BenAAndrew** [comment] 2021-04-09 19:24
Hi @gabcodedev, am I right in thinking you did the following:

1. Created a dataset in step 1
2. Went to the training step (step 2)
3. Selected your dataset from the dropdown and a number of epochs
4. Pressed start

And instead of showing the progress bar it opens a new tab?

**Comment by gabcodedev** [comment] 2021-04-09 20:54
@BenAAndrew I imported my own dataset, not created with your program. I did it with the import/export button at the top.
The rest that you said is correct, but the progress bar is shown but not filled with blue, just remains empty and after a few secs it opens a new tab with the main page (localhost:5000) if I switch to the previous tab (training tab) the progress bar remains empty. And yes I went directly to the training step (step 2) right after importing my dataset.

**Comment by BenAAndrew** [comment] 2021-04-10 11:34
@gabcodedev Do you have javascript disabled?

**Comment by gabcodedev** [comment] 2021-04-10 11:57
Javascript is enabled in my browser. I am using google chrome

**Comment by BenAAndrew** [comment] 2021-04-11 11:28
It's odd that it opens a new tab. When you try doing it, do you see any error messages in the app console?

**Comment by BenAAndrew** [comment] 2021-04-11 15:25
Hi @gabcodedev, I'm able to replicate the issue. I will update when fixed

**Comment by gabcodedev** [comment] 2021-04-11 15:33
@BenAAndrew Thanks for your help, really appreciate it.

**Comment by BenAAndrew** [comment] 2021-04-12 11:12
Hi @gabcodedev, this bug is a real head-scratcher. The issue seems to be with some unexpected behaviour of flask-socketio so I've raised an issue with them: https://github.com/miguelgrinberg/Flask-SocketIO/issues/1520. In the meanwhile, I'll carry on trying to resolve this issue as my number 1 priority.

**Comment by gabcodedev** [comment] 2021-04-13 12:26
@BenAAndrew Okay so I think I found the reason why this happens, it simply a memory error. Who do I know this? Because I cloned the repo and installed all the requirements, then I ran main.py and with 5000 epochs it actually throwed the actual error that was causing the weird behaviour with the precompiled executable. So I reduce the number of epoch to 1000 and trained and all worked fine.

**Comment by BenAAndrew** [comment] 2021-04-14 19:33
@gabcodedev, yeah the issue is related to it running in a thread. I'm working on switching all processes to subprocesses so that this is not an issue. Will update when done

**Comment by BenAAndrew** [comment] 2021-04-14 23:51
@gabcodedev I was unable to switch to subprocesses but was able to identify and fix the issue. This should be fixed in release 0.6

**Comment by BenAAndrew** [comment] 2021-04-18 18:59
Closing as this has been fixed in release 0.6.

**Closed by BenAAndrew** 2021-04-18 18:59 UTC
Labels: bug, help wanted
