### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by ManBearPig87** [BenAAndrew/Voice-Cloning-App#48] opened 2021-07-27 16:59 UTC
First time user - after uploading .txt and .wav I get the following error. Any guidance? 

Type: HTTPError
Text: HTTP Error 503: Service Temporarily Unavailable
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 99, in create_dataset_post File "dataset\transcribe.py", line 85, in create_transcription_model File "dataset\transcribe.py", line 58, in __init__ File "torch\hub.py", line 364, in load model = _load_local(repo_or_dir, model, *args, **kwargs) File "torch\hub.py", line 393, in _load_local model = entry(*args, **kwargs) File "C:\Users\Sam London/.cache\torch\hub\snakers4_silero-models_master\hubconf.py", line 28, in silero_stt **kwargs) File "C:\Users\Sam London/.cache\torch\hub\snakers4_silero-models_master\utils.py", line 128, in init_jit_model progress=True) File "torch\hub.py", line 419, in download_url_to_file u = urlopen(req) File "urllib\request.py", line 223, in urlopen File "urllib\request.py", line 532, in open File "urllib\request.py", line 642, in http_response File "urllib\request.py", line 570, in error File "urllib\request.py", line 504, in _call_chain File "urllib\request.py", line 650, in http_error_default urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Comment by BenAAndrew** [comment] 2021-07-27 17:03
Sounds like you've lost internet connection or the server for silero is down. Can you reach this link: https://models.silero.ai/models/en/en_v3_jit.model ?

**Comment by ManBearPig87** [comment] 2021-07-27 17:25
Yes, the link works, strange... I wonder if a firewall could be causing this issue

**Comment by ManBearPig87** [comment] 2021-07-27 17:26
Also thank you for the quick response!

**Comment by BenAAndrew** [comment] 2021-07-27 20:01
No problem. Does sound like a possible network issue on your side. The first time you use the app it needs to download data for the transcription tool which is why this is generating a network error.

**Comment by ManBearPig87** [comment] 2021-07-27 22:44
I'll dig in - does any of this seem relevant? From the executable script

[16408] WARNING: file already exists but should not:
C:\Users\SAMLON~1\AppData\Local\Temp\_MEI164082\torch\_C.cp36-win_amd64.pyd
Server initialized for threading.
Server initialized for threading.
INFO:matplotlib.font_manager:generated new fontManager
[nltk_data] Downloading package wordnet to C:\Users\SAMLON~1\AppData\L
[nltk_data]     ocal\Temp\_MEI164082\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
WARNING:werkzeug:WebSocket transport not available. Install eventlet or
gevent and gevent-websocket for improved performance.
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production
deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [27/Jul/2021 18:41:45] "GET / HTTP/1.1" 200 -
Using cache found in C:\Users\Sam
London/.cache\torch\hub\snakers4_silero-models_master
INFO:werkzeug:127.0.0.1 - - [27/Jul/2021 18:42:30] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [27/Jul/2021 18:42:30] "GET /favicon.ico
HTTP/1.1" 200 -

**Comment by ManBearPig87** [comment] 2021-07-28 14:09
So I tried a few things including copying the source code to root and now I'm getting the following - could this be a folder permissions issue? Sorry to be a pest, just really interested in demoing this software if I can get it to work :/

Type: OSError
Text: [Errno 22] Invalid argument: 'tmpmm96uy_m'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 98, in create_dataset_post File "dataset\transcribe.py", line 85, in create_transcription_model File "dataset\transcribe.py", line 58, in __init__ File "torch\hub.py", line 364, in load model = _load_local(repo_or_dir, model, *args, **kwargs) File "torch\hub.py", line 393, in _load_local model = entry(*args, **kwargs) File "C:\Users\Sam London/.cache\torch\hub\snakers4_silero-models_master\hubconf.py", line 22, in silero_stt progress=False) File "torch\hub.py", line 433, in download_url_to_file f = tempfile.NamedTemporaryFile(delete=False, dir=dst_dir) File "tempfile.py", line 551, in NamedTemporaryFile File "tempfile.py", line 262, in _mkstemp_inner OSError: [Errno 22] Invalid argument: 'tmpmm96uy_m'

**Comment by BenAAndrew** [comment] 2021-07-28 21:30
That's a weird one. Sounds like it's struggling to delete a temporary file but doesn't seem to be due to permissions.
If you are familiar with python could you try adding this to a script and executing it. Might make the issue clearer to solve

`
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model, decoder, _ = torch.hub.load(repo_or_dir="snakers4/silero-models", model="silero_stt", language="en", device=device)
`

**Comment by ManBearPig87** [comment] 2021-07-29 17:33
Unfortunately, not coding savvy but maybe I will spend some time with it. I did try to clear the files myself and start fresh and am still getting this error. Appreciate the efforts!

**Comment by BenAAndrew** [comment] 2021-07-29 19:49
Sorry to hear this. If you want you could join the discord where others may be able to propose solutions. Unfortunately, this issue is with https://github.com/snakers4/silero-models and I'm not familiar with their system. It may be worth sharing this issue on their repo to see if they have any suggestions.

**Comment by BenAAndrew** [comment] 2021-08-06 16:00
Any news on this?

**Comment by ManBearPig87** [comment] 2021-08-06 18:37
I've tried a few different approaches including removing all files manually
and reinstalling python, still no luck unfortunately! If I have time in the
future I may partition Linux and go that route

**Comment by BenAAndrew** [comment] 2021-08-10 09:14
Sounds like you've had some really bad luck with this. I haven't heard of anyone having this problem. Did you raise an issue on the silero github?

**Comment by BenAAndrew** [comment] 2021-08-18 16:05
Closing as the issue is not directly due to the app. Please reopen if you find a fix

**Closed by BenAAndrew** 2021-08-18 16:05 UTC
